name = "jsrs-web"
main = "@tanstack/react-start/server-entry"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "js.rs"
custom_domain = true

[[services]]
binding = "SVC_VERIFY"
service = "jsrs-svc-verify"

[observability]
enabled = true
