name = "jsrs-web"
main = "@tanstack/react-start/server-entry"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[[routes]]
pattern = "js.rs"
custom_domain = true

[observability]
enabled = true
